# Generated by Django 6.0.7 on 2026-07-23 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Used in the URL, e.g. edge-ai-iot', max_length=120, unique=True)),
                ('icon', models.CharField(help_text='Emoji icon, e.g. 🤖', max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short line shown on the domain box', max_length=200)),
                ('budget', models.CharField(default='₹2000 / team', help_text='e.g. ₹2000 / team', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='e.g. 1 for PS 1')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('context', models.TextField()),
                ('minimum_requirements', models.TextField(help_text='One requirement per line - rendered as a bullet list')),
                ('dependencies', models.TextField(help_text='One dependency per line - rendered as a bullet list')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='core.domain')),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=150)),
                ('weight', models.CharField(help_text='e.g. 30%', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('problem_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='core.problemstatement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
