# Generated by Django 5.0.14 on 2026-07-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sponsor_type', models.CharField(choices=[('TITLE', 'Title Sponsor'), ('TECHNICAL', 'Technical Sponsor')], default='TECHNICAL', max_length=10)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsors/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sponsor_type', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='context',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='dependencies',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Show this problem statement on the public tracks page.'),
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='min_requirements',
            field=models.TextField(blank=True, max_length=500, verbose_name='Minimum requirements'),
        ),
        migrations.AlterField(
            model_name='problemstatement',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
