# Generated by Django 5.0.14 on 2026-07-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderRegistration',
        ),
    ]
