# Generated by Django 5.0.14 on 2026-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sponsor_problemstatement_context_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['scheduled_at', 'name']},
        ),
        migrations.AddField(
            model_name='problemstatement',
            name='impact',
            field=models.TextField(blank=True, max_length=500, verbose_name='Impact'),
        ),
        migrations.AddField(
            model_name='review',
            name='weightage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage this round contributes to the total score.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
