# Generated by Django 5.0.14 on 2026-08-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_offline_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconfiguration',
            name='selection_frozen',
            field=models.BooleanField(default=False, help_text='Freeze participant Track and Problem Statement selections.'),
        ),
    ]
